name: 'PR Lint'
description: 'Lints your Pull Request for common mistakes'
inputs:
  token:
    description: 'Github token'
    required: true
outputs:
  output:
    description: 'Output'
runs:
  using: 'node12'
  main: 'dist/index.js'