name: 'PR Lint'
description: 'Lints your Pull Request for common mistakes'
inputs:
  repo-token:
    description: 'Github token'
    required: true
outputs:
  head:
    description: 'The head commit of the PR'
runs:
  using: 'node12'
  main: 'dist/index.js'