on: [pull_request]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    name: PR lint
    steps:
      - name: Run the linter
        id: lint
        uses: peej/pr-lint-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sniffs: pull/empty-body
      - name: Get the output
        run: echo "${{ steps.lint.outputs.output }}"